### ISSUE TITLE
"It's cross-browser compatible"

### ISSUE THREAD

**Issue by lucanos** [pazguille/voix#2]
The claim in the Readme, that this is "cross-browser compatible", but then only listing "Chrome" as a supported browser is akin to that old Henry Ford quote "You can have any color, as long as it's black."

Might be worth dropping that section until other browsers are supported.

**Comment by jeffgca** [comment]
I would assume this is just to indicate the _intention_ of offering better browser support.

**Comment by lucanos** [comment]
Sure, I understand that, but would you prefer documentation to state what is currently supported, or what is hoped to possibly be supported at a later stage (without that being clearly detailed)?
